[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "dj9Q3CpHvDHwexCbkgJ5APDx4JsTxPssNebkvP15g1T"
property = "deCp9srk9C6P4BXJaFpjR5H6Jsm6DCq8AL2kk338dVq"
regions = "5iupkzVtWxee48UXh3s615V9sXXuYjsSr61VPuduXdPc"
xcavate-whitelist = "7TrzjKpdrEhnfhxuw8tWdH1sjxadazscsG5HXCDPLmaY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
